### ISSUE TITLE
Is Natural Language Dates plugin really needed?

### ISSUE THREAD

**Issue by sanderdatema** [ryanjamurphy/vantage-obsidian#1]
I know your other plugin, Review, needs it. But this one complains about it as well. And with this error: "The Natural Language Dates plugin was not found. The **Review plugin** requires the Natural Language Dates plugin. Please install it first and make sure it is updated and enabled before using **Vantage**."

It looks like you copy/pasted the text from your other plugin. But now I'm confused... 🤪

I guess this is the line in the script:

https://github.com/ryanjamurphy/vantage-obsidian/blob/241a8bcf7f2a2f0a4519ef8d63582f235e6d324f/main.ts#L9

**Comment by ryanjamurphy** [comment]
Yes, NL Dates is used by Vantage to generate date-based searches of your daily notes. Sorry about the erroneous reference to Review.
