### ISSUE TITLE
Unable to load plugin with vault stored in iCloud Drive

### ISSUE THREAD

**Issue by brianmichel** [ryanjamurphy/vantage-obsidian#11]
Obsidian Version: 0.15.9
Plugin Version: 1.4.2

Whenever I try to turn on the Vantage plugin on my installation I get a toast in the top right corner of Obsidian saying that it failed to enable the plugin. When I toggle the developer tools I see the following errors in the console:

```
Plugin failure: vantage-obsidian Error: ENOENT: no such file or directory, open '/Users/brianmichel/Library/Mobile Documents/iCloud~md~obsidian/Documents/Brian's Obsidian/.obsidian/plugins/vantage-obsidian/main.js'
```

When I `cd` into that directory and take a look, these are the only files that I see:

<img width="789" alt="CleanShot 2022-10-12 at 20 29 28@2x" src="https://user-images.githubusercontent.com/63919/195471946-d11df75f-65b9-4260-9779-670bbfdc263b.png">

I've experienced this error on both macOS Monterrey and macOS Ventura. I initially thought that it might have something to do with my storing these files in iCloud Drive, but I'm less sure of that as other plugins seem to work just fine. Any ideas?

**Comment by ryanjamurphy** [comment]
Sorry, dumb error on my part (added the wrong file to the release). Should work now @brianmichel — try again?

**Comment by brianmichel** [comment]
Will give it a try ASAP and respond back here.

**Comment by brianmichel** [comment]
Just tried it and it works! Thanks for the quick fix, please consider the
issue closed.
