### ISSUE TITLE
Can't scroll to fill in rest of options

### ISSUE THREAD

**Issue by PaulFWatts** [ryanjamurphy/vantage-obsidian#3]
Have just installed Vantage for the 1st time using Version 1.1.0

Running Obsidian Version 0.11.3  on MacOS (Big Sur)

When running Vantage I can't scroll in the window that comes up to enter all the options or submit the search.

Have to expand the Obsidian window to see the bottom of the Vantage window.

Also tested this on Windows 10 and it has the same problem.

**Comment by jarodise** [comment]
Same on mac, the window size is too big that both the top and bottom are cropped, and there is no way to scroll up and down.

**Comment by ryanjamurphy** [comment]
Agree that this is an issue. I'm trying to find the best way to fix it—just making it scrollable leads to some ugly behaviour, but I might push that as a patch for now.

**Comment by desk7** [comment]
I have a similar issue. I use Obsdian 0.11.5 on my Windows 10 laptop (13.3" FHD) with a second monitor (32" 4K).
When I open Vantage window on the 13.3" laptop monitor, the window size is too big that both the top and bottom are cropped. Howerver, when I open it on the external monitor, I can't see the whole Vantage window without any problem.

**Comment by ryanjamurphy** [comment]
Apologies for the delay on this issue. This should be fixed with 1.3.0!
