### ISSUE TITLE
Text fields are difficult to see

### ISSUE THREAD

**Issue by thomaskern** [ryanjamurphy/vantage-obsidian#7]
This might be a styling issue but the text fields are hard to see since the borders are almost white.

Even now that I know where the fields are I cannot spot them easily.

![CleanShot 2021-06-14 at 22 25 49](https://user-images.githubusercontent.com/39680/121954900-93314900-cd5f-11eb-9893-bf45fea4508e.jpg)

**Comment by ryanjamurphy** [comment]
Interesting. I see your point, though I think this is a CSS issue—it's clearer, for instance, in the default CSS settings.

I'm just using the API text fields for this, so you can edit them pretty easily. You might want to try enabling a snippet like:
```
input[type='text'], input[type='search'], input[type='email'], input[type='password'], input[type='number'] {
    background: var(--background-modifier-form-field);
}
```

and if that specified variable doesn't exist in your settings, a simple white (`#ffffff`) would probably work.

**Comment by thomaskern** [comment]
@ryanjamurphy you are right indeed. I tried Dracula (which seems to be a dark one) and it looks much much better right away (ok, not the buttons but heyho)
![CleanShot 2021-06-14 at 22 37 54](https://user-images.githubusercontent.com/39680/121956279-3afb4680-cd61-11eb-8445-8fdff15aa902.jpg)
