### ISSUE TITLE
Mobile Help notes can't be dismissed

### ISSUE THREAD

**Issue by mlevison** [ryanjamurphy/vantage-obsidian#9]
IPhone 13 Pro Max - when I try to use Vantage search on my phone the search options and history display occupy all the screen real estate. It can't be dismissed and it obscures all of the search results.

Ideal solution - don't automatically display the help window, when the search field is empty.

FWIW I'm away from home and can't easily post a screen shot.

**Comment by ryanjamurphy** [comment]
@mlevison thanks for the report. Vantage needs a lot of tuning for mobile apps, admittedly. I haven't really put any effort into it yet. 

However, I'm not seeing problems as dramatic as you describe—I _can_ use Vantage, enter a search, then see the results. I'd love to see a screenshot or recording of the behaviour you're seeing if you get the chance.

**Comment by mlevison** [comment]
It was my screw up, I got Vantage search confused with the search built in to Obsidian itself. 

Honestly - Obsidian is incredibly powerful, not yet human friendly. However that isn't your fault.

**Comment by ryanjamurphy** [comment]
Fair! 

Yes, it's a tool that requires "sinking into." 

FWIW you can use the Hider plugin to hide help tooltips and the like. You might want to install it on mobile to see if it can clean up the UI for you!
